services:
  postgres:
    image: postgres:15
    container_name: rt-postgres
    environment:
      POSTGRES_DB: runtogether
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"                      
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U runner -d runtogether"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data: